service:
  image: johnjelinek/l4d2server
  ports:
    - "27015:27015/tcp"
    - "27015:27015/udp"
  volumes:
    - /var/docker/l4d2server:/home/l4d2server
  entrypoint: /home/l4d2server/serverfiles/srcds_run
  command: -game left4dead2 -strictportbind -ip 0.0.0.0 -port 27015 +clientport 27005 +map c5m1_waterfront +servercfgfile l4d2-server.cfg -maxplayers 8
